### ISSUE TITLE
[Request] 1.19.2 Backport

### ISSUE THREAD

**Issue by pikasalt** [ViktorP04/pet-armor-mod-1.20.X#1]
A lot of mods are still on 1.19.2 and still have not been updated to newer versions, would it be possible to backport?

**Comment by ViktorP04** [comment]
The "[Wolves With Armor](https://www.curseforge.com/minecraft/mc-mods/wolves-with-armor/files)" mod has all of this mods features and a lot more. It supports 1.19.2 (and earlier versions) so I suggest using it instead. 

The main reason this mod was developed was that there were no wolf armor mods for newer versions. So I see no reason to backport this when there are better alternatives
